from avl import AVL
if __name__ == '__main__':
    t = AVL()
    t.put(75,'apple')
    t.put(80,'grape')
    t.put(85,'lime')
    t.put(20,'mango')
    t.put(10,'strawberry')
    t.put(50,'banana')
    t.put(30,'cherry')
    t.put(40,'watermalon')
    t.put(70,'malon')
    t.put(90,'plum')
    print('전위순위:\t',end='')
    t.preorder(t.root)
    print('\n중회순위:\t',end='')
    t.inorder(t.root)
    print('\n75와 85 삭제 후:')
    t.delete(75)
    t.delete(85)
    print('전위순위:\t',end='')
    t.preorder(t.root)
    print('\n중회순위:\t',end='')
    t.inorder(t.root)

